### ISSUE TITLE
NoReverseMatch, using namespaced URLs

### ISSUE THREAD

**Issue by pandafulmanda** [Safox1/DjangoSite#1]
Hi!

For the error:

```
NoReverseMatch at /
Reverse for 'blog-home' not found. 'blog-home' is not a valid view function or pattern name.
```

that we saw yesterday, the issue is on these lines:

https://github.com/Safox1/DjangoSite/blob/eea0c2320f10eecdbfa1b0ee94c3e03201de8987/Mystore/blog/templates/blog/base.html#L30-L33
 
`blog-home` set up as a "namespaced" url.  This means any url for blogs require an extra `blog:` prefix, like this:

```html
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{% url 'blog:blog-home' %}">Home</a>
	          <a class="nav-item nav-link" href="{% url 'blog:blog-about' %}">About</a>
                </div>
```

The blog urls was namespaced by this line here:

https://github.com/Safox1/DjangoSite/blob/eea0c2320f10eecdbfa1b0ee94c3e03201de8987/Mystore/blog/urls.py#L4

It seems kinda hard to find information about the Django url namespacing feature?  But here's some resources:

* https://djangobook.com/advanced-views-urlconfs/#leanpub-auto-url-namespaces
* https://stackoverflow.com/questions/19171570/a-real-example-of-url-namespace

**Comment by Safox1** [comment]
Thank you sooo much. I will go fix that right now.
